## 로컬에서 실행할때는 아래와 같이 cloud.aws.stack.auto: false 을 추가해줘야 함.
cloud:
  aws:
    stack:
      auto: false
    end-point.uri: ## ex: https://sqs.ap-northeast-2.amazonaws.com/1234567890/jmlim-sqs
    region:
      static: ap-northeast-2 # ec2 환경이 아니므로