## 로컬에서 실행할때는 아래와 같이 cloud.aws.stack.auto: false 을 추가해줘야 함.
cloud.aws.stack.auto: false

cloud:
  aws:
    region:
      static: <리전정보 > # ap-northeast-2
      auto: false
    credentials:
      accessKey: <your accessKey> # AKIASBDAEEASEWE
      secretKey: <your secretKey> # CAspdkldkl+baboabaoboa/V4ACSJSDfbPtest3
    end-point:
      uri: https://sqs.ap-northeast-2.amazonaws.com/<YOUR ID, get this from SQS Console>/jmlim-sqs